export const games = [
  {
    id: "1",
    name: "Valorant",
    slug: "valorant",
    description: "5v5 tactical shooter",
    player_count: 12400,
    tournament_count: 24,
    theme: { primary: "0 90% 50%", secondary: "340 80% 55%", accent: "190 90% 50%" },
  },
  {
    id: "2",
    name: "League of Legends",
    slug: "league-of-legends",
    description: "5v5 MOBA",
    player_count: 28500,
    tournament_count: 42,
    theme: { primary: "45 100% 50%", secondary: "210 90% 55%", accent: "160 80% 45%" },
  },
  {
    id: "3",
    name: "Counter-Strike 2",
    slug: "counter-strike-2",
    description: "5v5 tactical FPS",
    player_count: 18900,
    tournament_count: 36,
    theme: { primary: "30 90% 50%", secondary: "200 80% 50%", accent: "50 90% 55%" },
  },
  {
    id: "4",
    name: "Rocket League",
    slug: "rocket-league",
    description: "3v3 vehicular soccer",
    player_count: 8200,
    tournament_count: 18,
    theme: { primary: "210 90% 55%", secondary: "270 80% 55%", accent: "30 90% 55%" },
  },
  {
    id: "5",
    name: "Apex Legends",
    slug: "apex-legends",
    description: "Battle royale FPS",
    player_count: 9500,
    tournament_count: 15,
    theme: { primary: "0 85% 55%", secondary: "220 80% 50%", accent: "160 85% 45%" },
  },
  {
    id: "6",
    name: "Fortnite",
    slug: "fortnite",
    description: "Battle royale",
    player_count: 15600,
    tournament_count: 22,
    theme: { primary: "260 80% 60%", secondary: "200 85% 55%", accent: "50 90% 55%" },
  },
];

export const tournaments = [
  {
    id: "1",
    name: "ArenaX Championship Series",
    game_name: "Valorant",
    game_id: "1",
    format: "single_elimination",
    status: "registration_open",
    max_teams: 32,
    registered_count: 24,
    prize_pool: "$10,000",
    start_date: "2026-03-15",
    registration_deadline: "2026-03-10",
    featured: true,
    region: "NA",
  },
  {
    id: "2",
    name: "Winter Clash Invitational",
    game_name: "League of Legends",
    game_id: "2",
    format: "double_elimination",
    status: "in_progress",
    max_teams: 16,
    registered_count: 16,
    prize_pool: "$25,000",
    start_date: "2026-02-20",
    registration_deadline: "2026-02-15",
    featured: true,
    region: "EU",
  },
  {
    id: "3",
    name: "Pro League Season 4",
    game_name: "Counter-Strike 2",
    game_id: "3",
    format: "round_robin",
    status: "registration_open",
    max_teams: 12,
    registered_count: 8,
    prize_pool: "$15,000",
    start_date: "2026-04-01",
    registration_deadline: "2026-03-25",
    featured: false,
    region: "NA",
  },
  {
    id: "4",
    name: "Rising Stars Cup",
    game_name: "Rocket League",
    game_id: "4",
    format: "swiss",
    status: "completed",
    max_teams: 16,
    registered_count: 16,
    prize_pool: "$5,000",
    start_date: "2026-01-10",
    registration_deadline: "2026-01-05",
    featured: false,
    region: "NA",
  },
  {
    id: "5",
    name: "Apex Predator Series",
    game_name: "Apex Legends",
    game_id: "5",
    format: "single_elimination",
    status: "registration_open",
    max_teams: 20,
    registered_count: 14,
    prize_pool: "$8,000",
    start_date: "2026-03-20",
    registration_deadline: "2026-03-15",
    featured: false,
    region: "EU",
  },
  {
    id: "6",
    name: "Sunday Showdown #12",
    game_name: "Fortnite",
    game_id: "6",
    format: "single_elimination",
    status: "draft",
    max_teams: 64,
    registered_count: 0,
    prize_pool: "$2,000",
    start_date: "2026-04-05",
    registration_deadline: "2026-04-01",
    featured: false,
    region: "NA",
  },
];

export const topPlayers = [
  { rank: 1, name: "PhantomX", game: "Valorant", rating: 2847, tier: "Champion", wins: 342, losses: 48, streak: 12 },
  { rank: 2, name: "NexusGod", game: "League of Legends", rating: 2791, tier: "Champion", wins: 520, losses: 91, streak: 8 },
  { rank: 3, name: "BlitzKrieg", game: "Counter-Strike 2", rating: 2688, tier: "Diamond", wins: 280, losses: 62, streak: 5 },
  { rank: 4, name: "VortexQ", game: "Valorant", rating: 2634, tier: "Diamond", wins: 215, losses: 55, streak: 15 },
  { rank: 5, name: "ShadowByte", game: "Apex Legends", rating: 2590, tier: "Diamond", wins: 198, losses: 67, streak: 3 },
  { rank: 6, name: "AceRunner", game: "Rocket League", rating: 2512, tier: "Platinum", wins: 310, losses: 102, streak: 7 },
  { rank: 7, name: "ZeroGravity", game: "Fortnite", rating: 2488, tier: "Platinum", wins: 175, losses: 58, streak: 4 },
  { rank: 8, name: "CyberWolf", game: "Valorant", rating: 2445, tier: "Platinum", wins: 290, losses: 110, streak: 6 },
  { rank: 9, name: "StormChaser", game: "League of Legends", rating: 2401, tier: "Gold", wins: 180, losses: 85, streak: 2 },
  { rank: 10, name: "IronPulse", game: "Counter-Strike 2", rating: 2367, tier: "Gold", wins: 220, losses: 98, streak: 9 },
];

export const teams = [
  { id: "1", name: "Phantom Esports", tag: "PHX", members: 5, rating: 2450, tier: "Diamond", wins: 48, losses: 12, game: "Valorant" },
  { id: "2", name: "Nexus Gaming", tag: "NXG", members: 5, rating: 2380, tier: "Diamond", wins: 52, losses: 18, game: "League of Legends" },
  { id: "3", name: "Storm Brigade", tag: "STB", members: 5, rating: 2210, tier: "Platinum", wins: 35, losses: 15, game: "Counter-Strike 2" },
  { id: "4", name: "Volt Racing", tag: "VLT", members: 3, rating: 2100, tier: "Platinum", wins: 28, losses: 12, game: "Rocket League" },
  { id: "5", name: "Apex Predators", tag: "APX", members: 3, rating: 1980, tier: "Gold", wins: 22, losses: 14, game: "Apex Legends" },
  { id: "6", name: "Shadow Collective", tag: "SHD", members: 4, rating: 1850, tier: "Gold", wins: 18, losses: 16, game: "Fortnite" },
];

export const rankTiers = {
  Champion: { color: "text-yellow-400", bg: "bg-yellow-400/10", border: "border-yellow-400/30", glow: "shadow-yellow-400/20" },
  Diamond: { color: "text-cyan-400", bg: "bg-cyan-400/10", border: "border-cyan-400/30", glow: "shadow-cyan-400/20" },
  Platinum: { color: "text-emerald-400", bg: "bg-emerald-400/10", border: "border-emerald-400/30", glow: "shadow-emerald-400/20" },
  Gold: { color: "text-amber-400", bg: "bg-amber-400/10", border: "border-amber-400/30", glow: "shadow-amber-400/20" },
  Silver: { color: "text-slate-300", bg: "bg-slate-300/10", border: "border-slate-300/30", glow: "shadow-slate-300/20" },
  Bronze: { color: "text-orange-400", bg: "bg-orange-400/10", border: "border-orange-400/30", glow: "shadow-orange-400/20" },
} as const;

export type RankTier = keyof typeof rankTiers;

export const statusColors: Record<string, { bg: string; text: string }> = {
  registration_open: { bg: "bg-success/20", text: "text-success" },
  in_progress: { bg: "bg-live/20", text: "text-live" },
  completed: { bg: "bg-muted", text: "text-muted-foreground" },
  draft: { bg: "bg-muted", text: "text-muted-foreground" },
  registration_closed: { bg: "bg-warning/20", text: "text-warning" },
  cancelled: { bg: "bg-destructive/20", text: "text-destructive" },
};
